include:
  - remote: 'https://gitlab.miracum.org/miracum/dqa/dqa_base_image/-/raw/master/importable.gitlab-ci.yml'

## For infos see here: https://gitlab.miracum.org/miracum/dqa/dqa_base_image/-/tree/development

variables:
  R_PKG_NAME: "DQAstats"
