include:
  - remote: 'https://gitlab.miracum.org/miracum/dqa/dqa_base_image/-/raw/master/importable.gitlab-ci.yml'

## Information: https://gitlab.miracum.org/miracum/dqa/dqa_base_image#import-ci-configuration-in-other-r-projects

variables:
  R_PKG_NAME: "DQAstats"
