default:
# no capital letters!
  examplecsv:
    # Directory of the file:
    dir: "./inst/demo_data/DQA_example_data.csv"

    # URL of the database:
    # url: localhost:1234

    # Username:
    # user: "username"

    # Password:
    # password: "password"

  examplecsv_target:
    # Directory of the file:
    dir: "./inst/demo_data/DQA_example_data.csv"

    # URL of the database:
    # url: localhost:1234

    # Username:
    # user: "username"

    # Password:
    # password: "password"
