default:
# no capital letters!
  examplecsv1:
    dir: "./inst/demo_data/DQA_example_data.csv"    # Directory of the file

  examplecsv2:
    dir: "./inst/demo_data/DQA_example_data.csv"    # Directory of the file

  exampleDB:
  # The servicename (here: "exampleDB") must match with 'source_system_name' in the MDR
    dbname: "db_name"       # The name of the database
    host: "192.168.1.1"     # The IP of the database
    port: 1234              # The Port of the database
    user: "testusr"         # Username for the database
    password: "testpw"      # Password for the darabase
